package-lock.json, package.json
=> npmのバージョンをfix

src/pages/api/proxy.ts
=> function to arrow

package-lock.json, package.json
=> add libs react-icons/swiper/next-auth

package-lock.json, package.json
react-three/drei を追加
- react-three/drei を追加
- 
=> Add react-three/drei

src/components/main.tsx, src/components/mainCanvas.tsx, src/components/moon.tsx
=> Insert moon

src/type/index.ts
moonquake dataの型定義をした
- やったことを書く（必須）
moonquake dataの型定義をした
=> add moonquake-type

package-lock.json, package.json, src/components/main.tsx, src/components/mapLibre.tsx, src/pages/index.tsx
=> maplibreの追加（暫定）

src/components/mapLibre.tsx, src/components/useMapLibre/index.ts
=> refactering mapLibre

src/components/useMapLibre/index.ts
=> URL change

src/components/main.tsx
=> fix zindex

src/components/header.tsx, src/components/main.tsx, src/components/useThree/mainCanvas.tsx, src/components/useThree/moon.tsx, src/type/option.ts, src/utils/fetchMoonquakeCSV.ts
Yearを範囲選択できるように
- RangeSliderを追加、その範囲の地震データのみ表示するように
- 再生ボタン(むりかも)
=> RangeSlider Year

src/pages/_document.tsx
=> bodyにoverflow hiddenを追加

src/components/main.tsx, src/components/panel.tsx, src/components/useThree/mainCanvas.tsx, src/components/useThree/moon.tsx, src/components/useThree/pin.tsx, src/type/moon.ts
地震データをクリックしたらデータを表示する
- 地震データをクリックしたらデータを表示する
- 選択されているデータはアニメーションを再生し続ける
=> Change detail

src/components/mapLibre.tsx, src/components/useMapLibre/index.ts, src/components/useMapLibre/moonQuake.ts
=> 地図に地震データ表示

src/components/header.tsx, src/components/main.tsx, src/components/useThree/moon.tsx, src/type/index.ts, src/type/option.ts
自動で回るようにした/サイドバーでオフにすると回転が止まるようにした
- やったことを書く（必須）
=> Impl auto-rotate

src/components/header.tsx, src/components/main.tsx, src/components/useThree/moon.tsx, src/type/moon.ts, src/type/option.ts
=> Typeでのフィルター実装

src/components/header.tsx, src/components/useHeader/footer.tsx
- フッターを作った
useheaderの中にfooterがあります、ごめんなさい
=> add footer

src/components/header.tsx, src/components/main.tsx, src/pages/index.tsx
- header背景色調整
- ボタン消した
- `vh` to `svh` (for iPhone)
=> 色調整、ボタン消した、vh to svh

src/components/header.tsx
=> fix Heading

src/components/mapLibre.tsx, src/components/useMapLibre/index.ts, src/components/useThree/mainCanvas.tsx, src/utils/useWideHeader.ts
スマホのMapのzoomの距離のしゅうせい
- スマホのMapのzoomの距離のしゅうせい
=> Fix map zoom

src/pages/_document.tsx, src/pages/index.tsx
- タイトルを付けた
- スマホでページ自体の拡大を禁止した
=> add viewport and title

src/components/panel.tsx
`magnitude`, `depth` になっていた、頭文字は大文字にするべき
- Panel の `magnitude`, `depth`の頭文字を大文字に
今日のPRで間違えてこうなってしまったっぽい、ごめん
=> Fix Pascal-case

src/components/useThree/earth.tsx, src/components/useThree/moon.tsx
=> Fix insert earth

src/components/mapLibre.tsx, src/components/useMapLibre/index.ts, src/components/useMapLibre/lngLatDisplay.tsx, src/type/index.ts, src/type/map.ts
=> 経度緯度情報、長さ表示機能

src/components/header.tsx, src/components/useHeader/displayHint.tsx
ヒントの表示
- やったことを書く（必須）
modalでヒント表示
英語のチェックしてほしい。説明書きがなんかパッとしないデザイン......
=> [add] display-modalHint

src/components/useMapLibre/lngLatDisplay.tsx
=> 経度が倍になっていたのを修正

src/components/header.tsx, src/components/hint.tsx, src/components/main.tsx, src/components/useHeader/infoBox.tsx, src/components/useHeader/layerRadio.tsx, src/components/useHeader/typeFilterSetting.tsx, src/components/useMapLibre/index.ts, src/components/useMapLibre/lngLatDisplay.tsx, src/type/option.ts
- レイヤーの機能を追加した
- 透明度、オンオフ、数種類のレイヤー切り替えが可能
- menuのスタイル調整
=> 2dマップでレイヤー機能を追加

src/components/mapLibre.tsx, src/components/useMapLibre/index.ts, src/components/useThree/earth.tsx
=> 地球をクリックするとNasaの名言が飛び出す機能

src/components/hint.tsx, src/components/main.tsx
https://github.com/yudai1204/nasa-hackathon-2023-yokohama/issues/93
- クリックしてね！という表示を出した
=> add click popup

public/moon_place2en.geojson
=> add location geojson

public/moon_place2en.geojson
=> 地名geojson増やした

src/components/main.tsx, src/components/mapLibre.tsx, src/components/useMapLibre/index.ts, src/components/useMapLibre/lngLatDisplay.tsx, src/components/useMapLibre/moonQuake.ts, src/components/useThree/OrbitControlsWrapper.tsx, src/components/useThree/mainCanvas.tsx, src/components/useThree/moon.tsx
=> 3Dでzoomした時に2Dで表示される位置を合わせた

src/components/useThree/moon.tsx
=> add apollo

src/type/option.ts
=> disable auto rotate
